version: 0.1.{build}

configuration:
- Debug
- Release

platform:
- Any CPU
- x64

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
before_build:
- cmd: >-
    nuget restore

    nuget restore  src\Malina.Antlr\packages.config -PackagesDirectory src\Malina.Antlr\packages
build:
  project: /Malina.sln
  verbosity: minimal
  parallel: true
  
test:
  assemblies: '**\*.tests.dll'
  
artifacts:
  - path: 'build'